---
root: true
env:
  node: true
parser: "@typescript-eslint/parser"
parserOptions:
  project: true
  tsconfigRootDir: "__dirname"
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
plugins:
  - "@typescript-eslint"
